root: true
extends: 
  - eslint:recommended
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:chai-expect/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - chai-friendly
  - chai-expect
env:
  node: true
  mocha: true
rules:
  max-len:
   - 1
   - 120 